### ISSUE TITLE
DiscoRhythm app doesnt load from the link and keep crashing when you star it from R studio

### ISSUE THREAD

**Issue by dzamila24** [matthewcarlucci/DiscoRhythm#5]
It always crashes when you try to upload your csv file.

**Comment by matthewcarlucci** [comment]
Hello, thank you for the notification that the public server was not loading. A reset of the server seems to have resolved this.

For your other issue, if I understand correctly, you are starting DiscoRhythm in the Rstudio console with:

```
discoApp()
```

And then, the upload of your CSV results in the application crashing. 

To investigate this I would need:

1. The error message from the Rstudio console or elsewhere
2. Your CSV file, or a simplified version of it (which returns the same error) for testing purposes 
3. Your output from executing `sessionInfo()`

Thank you!

**Comment by dzamila24** [comment]
Hi,
I'm sorry it seems that the problem was on my side.....I didn't replace ,
by .  in my csv file and apparently it was the reason why the app always
crashed when I upload my data set.

Thank you for your time.
Cheers,

Kamila
